[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["cd server && npm run build || echo 'No build script found'"]

[start]
cmd = "cd server && npm start"
